# Generated by Django 4.2.13 on 2024-05-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['-time_create'], name='movies_movi_time_cr_9d7cf2_idx'),
        ),
    ]
