# Generated by Django 4.2.13 on 2024-08-24 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор поста'),
        ),
        migrations.AddField(
            model_name='movie',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list', to='movies.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='movie',
            name='people_roles',
            field=models.ManyToManyField(blank=True, related_name='movies_roles', through='movies.MoviePersonRole', to='movies.person', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='movies.tagpost', verbose_name='Жанр'),
        ),
        migrations.AlterUniqueTogether(
            name='moviepersonrole',
            unique_together={('movie', 'person', 'role')},
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['-time_create'], name='movies_movi_time_cr_130846_idx'),
        ),
    ]
