# Generated by Django 4.2.13 on 2024-05-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_options_movies_slug_alter_movies_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
