# Generated by Django 4.2.13 on 2024-05-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_category_movies_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.category'),
        ),
    ]
