# Generated by Django 4.2.13 on 2024-05-24 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_tagpost_alter_movies_cat_movies_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('movie', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='movies.movies')),
            ],
        ),
    ]
