# Generated by Django 4.2.13 on 2024-05-25 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_movies_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='moviedetails',
            name='movie',
        ),
        migrations.AddField(
            model_name='movies',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.moviedetails'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Имя на русском')),
                ('name_en', models.CharField(max_length=100, verbose_name='Имя латиницей')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('role', models.ManyToManyField(blank=True, related_name='person', to='movies.role')),
            ],
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='person',
            field=models.ManyToManyField(blank=True, related_name='details', to='movies.person'),
        ),
    ]
