# Generated by Django 4.2.13 on 2024-05-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_role_remove_moviedetails_movie_movies_details_person_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
        migrations.RenameIndex(
            model_name='movie',
            new_name='movies_movi_time_cr_130846_idx',
            old_name='movies_movi_time_cr_9d7cf2_idx',
        ),
    ]
