# Generated by Django 4.2.13 on 2024-08-09 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_rename_movies_movie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-time_create'], 'verbose_name': 'кино', 'verbose_name_plural': 'Фильмы и сериалы'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AddField(
            model_name='person',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list', to='movies.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='movies.moviedetails', verbose_name='Детали'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(choices=[(False, 'Черновик'), (True, 'Опубликовано')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='movies.tagpost', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время изменения'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='persons/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.ManyToManyField(blank=True, related_name='person', to='movies.role', verbose_name='Деятельность'),
        ),
    ]
