# Generated by Django 4.2.13 on 2024-08-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_options_alter_tagpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Латиницей'),
        ),
    ]
