# Generated by Django 4.2.13 on 2024-08-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Латиницей'),
        ),
    ]
