# Generated by Django 4.2.13 on 2024-08-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_alter_role_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Участник фильма', 'verbose_name_plural': 'Участники фильмов'},
        ),
    ]
