# Generated by Django 4.2.13 on 2024-08-13 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_person_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='people',
        ),
        migrations.CreateModel(
            name='MoviePersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_roles', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_roles', to='movies.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_in_movie', to='movies.role')),
            ],
            options={
                'verbose_name': 'Участник фильма и его роль',
                'verbose_name_plural': 'Участники фильмов и их роли',
                'unique_together': {('movie', 'person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='people_roles',
            field=models.ManyToManyField(related_name='movies_roles', through='movies.MoviePersonRole', to='movies.person', verbose_name='Участники'),
        ),
    ]
