# Generated by Django 4.2.13 on 2024-08-13 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_remove_person_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepersonrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_movie', to='movies.role'),
        ),
    ]
