# Generated by Django 4.2.13 on 2024-08-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_moviepersonrole_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Английское название'),
        ),
    ]
