# Generated by Django 4.2.13 on 2024-08-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_alter_movie_slug_alter_movie_title_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='people_roles',
            field=models.ManyToManyField(blank=True, related_name='movies_roles', through='movies.MoviePersonRole', to='movies.person', verbose_name='Участники'),
        ),
    ]
